### ISSUE TITLE
Version 1.4.4 || Uncaught ReferenceError: jsVectorMap is not defined

### ISSUE THREAD

**Issue by Mgrmjp** [themustafaomar/jsvectormap#69]
Barebones project and trying to use the package. Getting this in console:

```javascript
Uncaught ReferenceError: jsVectorMap is not defined
    at Object.3r67O ((index):2496:1)
    at newRequire ((index):89:24)
    at localRequire ((index):101:14)
    at Object.5HwUs.lodash/range ((index):490:16)
    at newRequire ((index):89:24)
    at localRequire ((index):101:14)
    at Object.fUiC5../app.js ((index):480:14)
    at newRequire ((index):89:24)
    at (index):138:5
    at (index):161:3

3r67O @ (index):2496
newRequire @ (index):89
localRequire @ (index):101
5HwUs.lodash/range @ (index):490
newRequire @ (index):89
localRequire @ (index):101
fUiC5../app.js @ (index):480
newRequire @ (index):89
(anonymous) @ (index):138
(anonymous) @ (index):161
```

Downgrading to 1.3.3 worked, but what might be the problem?

Importing like so:

```javascript
import 'jsvectormap';
import 'jsvectormap/dist/maps/world.js';

const map = new jsVectorMap({
  selector: '#map',
  map: 'world',
});

```

Installed via **npm**. Node version **14.19.0**.

**Comment by themustafaomar** [comment]
Hi @Mgrmjp 

There's was a typo in the documentation website and readme file about `import` statement, sorry for that.

It's fixed now, you can import like so:

```js
import jsVectorMap from 'jsvectormap'
import 'jsvectormap/dist/maps/world.js'

const map = new jsVectorMap({
  selector: '#map',
  map: 'world',
})
```

**Comment by Mgrmjp** [comment]
Still doing the same even after changing the import. 😢

**Comment by Mgrmjp** [comment]
That didn't seem to help either. 😂

Maybe it's something on my end. 🤷🏻‍♂️

**Comment by themustafaomar** [comment]
🤷🏻‍♂️

https://codesandbox.io/s/jvm-temp-workaround-iqp6rj

**Comment by rushenn** [comment]
> 🤷🏻‍♂️
> 
> https://codesandbox.io/s/jvm-temp-workaround-iqp6rj

Try to change the jsvectormap version to 1.4.4, the issue is still present.

**Comment by themustafaomar** [comment]
@rushenn Gonna publish a new version today which fixes the issue.

**Comment by themustafaomar** [comment]
Please update to v1.4.5 https://iqp6rj.csb.app/
